### ISSUE TITLE
Minor issues in evaluation report created with v10

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/Vancomycin-Model#9]
Attached are some comments of the evaluation report for vancomycin created with v10
[Vancomycin_evaluation_report_AD.pdf](https://github.com/Open-Systems-Pharmacology/Vancomycin-Model/files/7337648/Vancomycin_evaluation_report_AD.pdf)

@Incei

**Comment by Yuri05** [comment]
fixed with last PR
